[book]
title = "はじめてのウェブサイト"
# title = "日本語キーボード"
authors = ["Osamu377"]
language = "ja-JP"

[output.html]
additional-js = ["src/assets/fzf.umd.js", "src/assets/elasticlunr.js"]

[output.epub]
cover-image = "Designer.png"
